version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOODUSER: lucas.allain
        UID: 1000
        MAIL: lucas.allain@etu.univ-orleans.fr
        NOM: "Lucas ALLAIN"
    container_name: my-good-container
    volumes:
    - ./dev:/var/www/html
    ports:
    - "5000:8000"
    environment:
      PHP_IDE_CONFIG: serverName=toto
