package fr.univ.orleans.pnt.controleur.ordres;

public enum TypeOrdre {
    SHOW_ACCUEIL,
    SHOW_DETAIL_PERSONNE,
    SHOW_FORMULAIRE,
    SHOW_PERSONNES,
    ERREUR_ANNEE_SUPERIEURE_1900_ATTENDUE,
    ERREUR_ANNEE_SUPERIEURE_ANNEE_COURANTE,ERREUR_DONNEE_INCORRECTE,
    ERREUR_EMAIL_INCORRECT,
    ERREUR_ENTIER_ATTENDU,
    ERREUR_NUMERO_TELEPHONE_PORTABLE,
    DATA_NOUVELLE_PERSONNE_ENREGISTREE,
    DATA_PERSONNE_SELECTIONNEE,
}
